version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/sre.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    build: ./app
    ports:
      - 4567:4567
